S1_position_controller:
  type: position_controllers/JointPositionController
  joint: S1

S2_position_controller:
  type: position_controllers/JointPositionController
  joint: S2

S3_position_controller:
  type: position_controllers/JointPositionController
  joint: S3

E1_position_controller:
  type: position_controllers/JointPositionController
  joint: E1

E2_position_controller:
  type: position_controllers/JointPositionController
  joint: E2

W1_position_controller:
  type: position_controllers/JointPositionController
  joint: W1

W2_position_controller:
  type: position_controllers/JointPositionController
  joint: W2
