la_S1_position_controller:
  type: sr_mechanism_controllers/SrhJointPositionController
  joint: la_S1
  pid:
    p: 50.0
    deadband: 0.0
    friction_deadband: 2000.0
    i: 5.0
    d: 50.0
    max_force: 100.0
    i_clamp: 100.0
    position_deadband: 0.014999999999999999

la_S2_position_controller:
  type: sr_mechanism_controllers/SrhJointPositionController
  joint: la_S2
  pid:
    p: 50.0
    deadband: 0.0
    friction_deadband: 2000.0
    i: 5.0
    d: 50.0
    max_force: 100.0
    i_clamp: 100.0
    position_deadband: 0.014999999999999999


la_S3_position_controller:
  type: sr_mechanism_controllers/SrhJointPositionController
  joint: la_S3
  pid:
    p: 50.0
    deadband: 0.0
    friction_deadband: 2000.0
    i: 5.0
    d: 50.0
    max_force: 100.0
    i_clamp: 100.0
    position_deadband: 0.014999999999999999


la_E1_position_controller:
  type: sr_mechanism_controllers/SrhJointPositionController
  joint: la_E1
  pid:
    p: 50.0
    deadband: 0.0
    friction_deadband: 2000.0
    i: 5.0
    d: 50.0
    max_force: 100.0
    i_clamp: 100.0
    position_deadband: 0.014999999999999999


la_E2_position_controller:
  type: sr_mechanism_controllers/SrhJointPositionController
  joint: la_E2
  pid:
    p: 50.0
    deadband: 0.0
    friction_deadband: 2000.0
    i: 5.0
    d: 50.0
    max_force: 100.0
    i_clamp: 100.0
    position_deadband: 0.014999999999999999


la_W1_position_controller:
  type: sr_mechanism_controllers/SrhJointPositionController
  joint: la_W1
  pid:
    p: 50.0
    deadband: 0.0
    friction_deadband: 2000.0
    i: 5.0
    d: 50.0
    max_force: 100.0
    i_clamp: 100.0
    position_deadband: 0.014999999999999999


la_W2_position_controller:
  type: sr_mechanism_controllers/SrhJointPositionController
  joint: la_W2
  pid:
    p: 50.0
    deadband: 0.0
    friction_deadband: 2000.0
    i: 5.0
    d: 50.0
    max_force: 100.0
    i_clamp: 100.0
    position_deadband: 0.014999999999999999

